export const queryKeyCustomerUmrohPackage = {
  CUSTOMER_UMROH_PACKAGE_LIST: 'CUSTOMER_UMROH_PACKAGE_LIST',
  CUSTOMER_UMROH_PACKAGE_FILTER: 'CUSTOMER_UMROH_PACKAGE_FILTER',
  CUSTOMER_UMROH_PACKAGE_FILTER_THEMATICS: 'CUSTOMER_UMROH_PACKAGE_FILTER_THEMATICS',
  CUSTOMER_UMROH_PACKAGE_FILTER_TOUR_LEADERS: 'CUSTOMER_UMROH_PACKAGE_FILTER_TOUR_LEADERS',
  CUSTOMER_UMROH_PACKAGE_FILTER_TOUR_DESTINATIONS: 'CUSTOMER_UMROH_PACKAGE_FILTER_TOUR_DESTINATIONS',
  CUSTOMER_UMROH_PACKAGE_FILTER_AGENCY: 'CUSTOMER_UMROH_PACKAGE_FILTER_AGENCY',
  CUSTOMER_UMROH_PACKAGE_FILTER_FACILITY: 'CUSTOMER_UMROH_PACKAGE_FILTER_FACILITY',
  CUSTOMER_UMROH_PACKAGE_FILTER_AIRPORT: 'CUSTOMER_UMROH_PACKAGE_FILTER_AIRPORT',
  CUSTOMER_UMROH_PACKAGE_FILTER_AIRLINE: 'CUSTOMER_UMROH_PACKAGE_FILTER_AIRLINE',
  CUSTOMER_UMROH_PACKAGE_FILTER_DEPARTURE_MONTH: 'CUSTOMER_UMROH_PACKAGE_FILTER_DEPARTURE_MONTH',
}
