export const queryKeyMitraPackage = {
  MITRA_PACKAGE_LIST: 'MITRA_PACKAGE_LIST',
  MITRA_PACKAGE_DETAIL: 'MITRA_PACKAGE_DETAIL',

  FORM_PACKAGE_AIRLINES_LIST: 'FORM_PACKAGE_AIRLINES_LIST',
  FORM_PACKAGE_AIRLINES_DETAIL: 'FORM_PACKAGE_AIRLINES_DETAIL',
}
