export const queryKeyCustomerTransactionsHistory = {
  CUSTOMER_TRANSACTIONS_HISTORY_LIST: 'CUSTOMER_TRANSACTIONS_HISTORY_LIST',
  CUSTOMER_TRANSACTIONS_HISTORY_DETAIL: 'CUSTOMER_TRANSACTIONS_HISTORY_DETAIL',
}
