export const queryKeyCustomerTransactions = {
  CUSTOMER_TRANSACTION_LIST: 'CUSTOMER_TRANSACTION_LIST',
  CUSTOMER_TRANSACTION_DETAIL: 'CUSTOMER_TRANSACTION_DETAIL',
  CUSTOMER_TRANSACTION_PACKAGE: 'CUSTOMER_TRANSACTION_PACKAGE',
}
