export const queryKeyMasterCity = {
  DUMMY_MASTER_CITY_LIST: 'DUMMY_MASTER_CITY_LIST',
  DUMMY_MASTER_CITY_DETAIL: 'DUMMY_MASTER_CITY_DETAIL',

  MASTER_CITY_LIST: 'MASTER_CITY_LIST',
  MASTER_CITY_DETAIL: 'MASTER_CITY_DETAIL',
}
