export const queryKeyCustomerVisas = {
  DUMMY_CUSTOMER_VISA_LIST: 'DUMMY_CUSTOMER_VISA_LIST',
  DUMMY_CUSTOMER_VISA_DETAIL: 'DUMMY_CUSTOMER_VISA_DETAIL',

  CUSTOMER_VISA_LIST: 'CUSTOMER_VISA_LIST',
  CUSTOMER_VISA_DETAIL: 'CUSTOMER_VISA_DETAIL',
}
