export const queryKeyMasterProvider = {
  MASTER_PROVIDER_LIST: 'MASTER_PROVIDER_LIST',
  MASTER_PROVIDER_LIST_DELETE: 'MASTER_PROVIDER_LIST_DELETE',
  MASTER_PROVIDER_DETAIL: 'MASTER_PROVIDER_DETAIL',
}
