export const queryKeyMasterBanners = {
  DUMMY_MASTER_BANNER_LIST: 'DUMMY_MASTER_BANNER_LIST',
  DUMMY_MASTER_BANNER_DETAIL: 'DUMMY_MASTER_BANNER_DETAIL',

  MASTER_BANNER_LIST: 'MASTER_BANNER_LIST',
  MASTER_BANNER_DETAIL: 'MASTER_BANNER_DETAIL',
}
