export const queryKeyMasterThematics = {
  DUMMY_MASTER_THEMATIC_LIST: 'DUMMY_MASTER_THEMATIC_LIST',
  DUMMY_MASTER_THEMATIC_DETAIL: 'DUMMY_MASTER_THEMATIC_DETAIL',

  MASTER_THEMATIC_LIST: 'MASTER_THEMATIC_LIST',
  MASTER_THEMATIC_DETAIL: 'MASTER_THEMATIC_DETAIL',
}
