export const queryKeyCustomerPackageDetail = {
  CUSTOMER_UMROH_PACKAGE_DETAIL: 'CUSTOMER_UMROH_PACKAGE_DETAIL',
  CUSTOMER_UMROH_PACKAGE_DETAIL_FACILITY: 'CUSTOMER_UMROH_PACKAGE_DETAIL_FACILITY',
  CUSTOMER_UMROH_PACKAGE_DETAIL_AIRLINES: 'CUSTOMER_UMROH_PACKAGE_DETAIL_AIRLINES',
  CUSTOMER_UMROH_PACKAGE_DETAIL_PRICE: 'CUSTOMER_UMROH_PACKAGE_DETAIL_PRICE',
  CUSTOMER_UMROH_PACKAGE_DETAIL_ACCOMODATION: 'CUSTOMER_UMROH_PACKAGE_DETAIL_ACCOMODATION',
  CUSTOMER_UMROH_PACKAGE_DETAIL_SCHEDULE: 'CUSTOMER_UMROH_PACKAGE_DETAIL_SCHEDULE',
  CUSTOMER_UMROH_PACKAGE_DETAIL_TOUR_DESTINATION: 'CUSTOMER_UMROH_PACKAGE_DETAIL_TOUR_DESTINATION',
  CUSTOMER_UMROH_PACKAGE_DETAIL_TOUR_LEADER: 'CUSTOMER_UMROH_PACKAGE_DETAIL_TOUR_LEADER',
  CUSTOMER_UMROH_PACKAGE_DETAIL_IMAGE: 'CUSTOMER_UMROH_PACKAGE_DETAIL_IMAGE',
}

//tes
